### ISSUE TITLE
Location of opcua-gateway.jar has changed

### ISSUE THREAD

**Issue by haraldmeyer** [thin-edge/opcua-device-gateway-container#9]
the version number is no longer part of the file name but the jar now resides within a subfolder.

**Comment by reubenmiller** [comment]
@haraldmeyer  Do you think it is safe to change the default OPCU image to [1020.62.0/](https://resources.cumulocity.com/examples/opc-ua/) now since most of the public Cumulocity IoT instances are on 1020.x now (iirc)

**Comment by haraldmeyer** [comment]
Why not link to the folder http://resources.cumulocity.com/examples/opc-ua/ like the official OPC-UA documentation does and have the user make the call about the right version number to use?

**Comment by reubenmiller** [comment]
> Why not link to the folder http://resources.cumulocity.com/examples/opc-ua/ like the official OPC-UA documentation does and have the user make the call about the right version number to use?

The whole point of this repo was to create a dockerized version of the opcua-device-gateway so it could be used plug and play with thin-edge.io...so we don't actually want people to built it themselves.

So I guess we'll just build multiple versions (one per release, for the last x releases), then people have an ready-to-go image that can be deployed via the [tedge-container-plugin](https://github.com/thin-edge/tedge-container-plugin)

**Comment by reubenmiller** [comment]
And if they're building it themselves, then can already specify the build-arg `VERSION` to choose which version to use (at least since #10 was merged)

**Comment by haraldmeyer** [comment]
yes, you just need to switch from the version number being part of the filename to it being a path element

**Comment by reubenmiller** [comment]
> yes, you just need to switch from the version number being part of the filename to it being a path element

Though this is already solved by the linked PR...so it was more of a related question about what default value to use...

But anyway, I've created a new PR #11 to build one per release.
